# PayPal Configuration
paypal.clientId=Ad8nA7bOcya5jIjSkhk7jpylfRVr9k8hqE31rBKJYMwtGpq_L7_LMV6dWVey-edTAck_6cnq352M86Dr
paypal.clientSecret=EMWAWscq_xqijo8GfLBqeV9582gO3cngt-kcyWmOEIRM11uY2DEeQx_RLX5DDw0QBXsEG8oF2cVsGuVv
paypal.mode=sandbox
